### ISSUE TITLE
linux crash

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc-desktop#2]
well, maybe my linux has problems running snap. in any case, I got this when I tried to start it. Then it was just sitting there doing nothing…

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'electron-window-state'
Require stack:
- /snap/cocalc-desktop/x1/resources/app.asar/window.js
- /snap/cocalc-desktop/x1/resources/app.asar/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:261:1128)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/snap/cocalc-desktop/x1/resources/app.asar/window.js:2:27)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
```

**Comment by williamstein** [comment]
I will remove that snap binary. Linux users are really not the target audience for this. They are surely sophisticated enough to install node, got flown the repo, do “npm ci” and “npm start”....

**Comment by haraldschilly** [comment]
yes, I agree. Also if possible, this should be an AppImage.
